// Concatenates src/*.css (sorted by file name) into dist/jellyflix.css.
// Any @import rules found in the sources are hoisted to the top of the bundle,
// because CSS ignores @import that is not placed before all other rules.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'src');
const distDir = join(root, 'dist');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const files = readdirSync(srcDir).filter(f => f.endsWith('.css')).sort();
const imports = [];
const bodies = [];

for (const file of files) {
    const css = readFileSync(join(srcDir, file), 'utf8').replace(/\r\n/g, '\n');
    const body = css.replace(/^@import[^;]+;\s*$/gm, (rule) => {
        if (!imports.includes(rule.trim())) imports.push(rule.trim());
        return '';
    });
    bodies.push(`/* ==== ${file} ==== */\n${body.trim()}\n`);
}

const header = `/*!
 * JellyFlix v${pkg.version} - Netflix-inspired theme for Jellyfin 12.x (web client)
 * Built from ${files.length} modules. Do not edit this file - edit src/*.css and run \`npm run build\`.
 */
`;

mkdirSync(distDir, { recursive: true });
const out = header + (imports.length ? imports.join('\n') + '\n\n' : '') + bodies.join('\n');
writeFileSync(join(distDir, 'jellyflix.css'), out);
console.log(`dist/jellyflix.css: ${files.length} modules, ${imports.length} @import, ${(out.length / 1024).toFixed(1)} KiB`);
